configuration:
  swagger:
    app: 'Fitness Tracker'
    description: 'A simple fitness tracker built with Spring Boot'
    developer: 'Lejla MuratoviÄ‡'
    email: 'lejla.muratovic@stu.ibu.edu.ba'

spring:
    data:
      mongodb:
        uri: mongodb+srv://new-user:Wfr9otMo6UqxJAxT@cluster0.fxeeeps.mongodb.net/?retryWrites=true&w=majority
        database: fitness_tracker
    profiles:
      active: local

security:
  jwt:
    secret: 'y28p1VqHUQSJeLt39cDmgDcvNnCFef1c1Sm8crf3ZwBLmCXGSl'

